using AssignmentSubmissionSystem.Application.Abstractions;
using AssignmentSubmissionSystem.Application.Options;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AssignmentSubmissionSystem.Infrastructure.Storage;

/// <summary>
/// Writes uploads to a directory on the local filesystem.
/// </summary>
/// <remarks>
/// The fallback provider, so a fresh <c>docker compose up</c> works for an evaluator who has
/// no Cloudinary account. Backed by a named volume in compose; without one the files are lost
/// when the container is recreated, which is why this is not the choice for a real deployment.
/// </remarks>
public sealed class LocalFileStorage : IFileStorage
{
    public const string Provider = StorageOptions.ProviderLocal;

    private readonly string rootPath;
    private readonly ILogger<LocalFileStorage> logger;

    public LocalFileStorage(IOptions<StorageOptions> options, ILogger<LocalFileStorage> logger)
    {
        rootPath = Path.GetFullPath(options.Value.LocalRootPath);
        this.logger = logger;

        Directory.CreateDirectory(rootPath);
    }

    public string ProviderName => Provider;

    public async Task<StoredFile> SaveAsync(
        Stream content,
        string fileName,
        string contentType,
        CancellationToken cancellationToken)
    {
        // The key is generated, never derived from the client's file name. A name like
        // "../../etc/passwd" or "..\\config" therefore has nowhere to go: it is stored as
        // display metadata on the row and never touches the path.
        var storageKey = $"{Guid.NewGuid():N}";
        var fullPath = ResolveWithinRoot(storageKey);

        await using var destination = new FileStream(
            fullPath,
            FileMode.CreateNew,
            FileAccess.Write,
            FileShare.None,
            bufferSize: 81920,
            useAsync: true);

        await content.CopyToAsync(destination, cancellationToken);

        return new StoredFile(storageKey, destination.Length);
    }

    public Task<FileContent> OpenReadAsync(string storageKey, CancellationToken cancellationToken)
    {
        var fullPath = ResolveWithinRoot(storageKey);

        if (!File.Exists(fullPath))
        {
            throw new FileNotFoundException($"Stored file '{storageKey}' is missing from local storage.", fullPath);
        }

        Stream stream = new FileStream(
            fullPath,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            bufferSize: 81920,
            useAsync: true);

        // The real content type lives on the attachment row; the caller overrides this.
        return Task.FromResult(new FileContent(stream, "application/octet-stream"));
    }

    public Task DeleteAsync(string storageKey, CancellationToken cancellationToken)
    {
        var fullPath = ResolveWithinRoot(storageKey);

        try
        {
            File.Delete(fullPath);
        }
        catch (IOException ex)
        {
            // Matches the Cloudinary provider: the row is gone, so surfacing this as a request
            // failure would misreport the outcome. Recorded so orphans are traceable.
            logger.LogWarning(ex, "Failed to delete local file {StorageKey}. It may be orphaned.", storageKey);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Maps a storage key to an absolute path and refuses anything that escapes the root.
    /// Keys are generated by this class, so a traversal attempt means a tampered or corrupted
    /// database row — worth failing loudly rather than reading an arbitrary file off the disk.
    /// </summary>
    private string ResolveWithinRoot(string storageKey)
    {
        var candidate = Path.GetFullPath(Path.Combine(rootPath, storageKey));

        if (!candidate.StartsWith(rootPath + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && candidate != rootPath)
        {
            throw new InvalidOperationException($"Storage key '{storageKey}' resolves outside the storage root.");
        }

        return candidate;
    }
}
